server:
  port: 8080
  servlet:
    context-path: /QuanLyDuLich
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/QuanLyDuLich"
    username: root
    password: phu123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Sz2B4cavWkmDSMCJGf/yyj2+xMbcbawy50MV1oJHz/qbAHV91byX95w6prMSkxrv"