server:
  port: 8080
  servlet:
    context-path: /QuanLyDuLich
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/QuanLyDuLich?useUnicode=true&characterEncoding=UTF-8"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: quyvo2079@gmail.com
    password: ygdyexkaoeroddtc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "Sz2B4cavWkmDSMCJGf/yyj2+xMbcbawy50MV1oJHz/qbAHV91byX95w6prMSkxrv"

vnpay:
  tmn-code: 9WR33BBN
  hash-secret: EV9C0G1079UVL85Q963OPGSOY6BLNTON
  base-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/vnpay/payment/vnpay-callback
  version: 2.1.0
  command: pay
  curr-code: VND
  locale: vn

timezone:
  id: Asia/Ho_Chi_Minh